"""update_models_for_production

Revision ID: 5fe82634115e
Revises: 98aaaef59087
Create Date: 2026-06-30 14:06:39.496477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe82634115e'
down_revision = '98aaaef59087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rule_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_alerts_ip_id'), ['ip_id'], unique=False)
        batch_op.create_foreign_key('fk_alerts_event_id', 'security_events', ['event_id'], ['id'])
        batch_op.create_foreign_key('fk_alerts_ip_id', 'ip_addresses', ['ip_id'], ['id'])

    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_iso', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('asn_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('network_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('network_cidr', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('org_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('isp', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_tor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_vpn', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_hosting', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_proxy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('risk_factors', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ip_addresses_ip'), ['ip'], unique=True)
        batch_op.drop_column('network')

    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('raw_line', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('event_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_security_events_ip_id'), ['ip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_username'))
        batch_op.drop_index(batch_op.f('ix_security_events_ip_id'))
        batch_op.drop_column('event_timestamp')
        batch_op.drop_column('raw_line')
        batch_op.drop_column('description')

    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_ip_addresses_ip'))
        batch_op.drop_column('risk_factors')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('is_proxy')
        batch_op.drop_column('is_hosting')
        batch_op.drop_column('is_vpn')
        batch_op.drop_column('is_tor')
        batch_op.drop_column('isp')
        batch_op.drop_column('org_name')
        batch_op.drop_column('network_cidr')
        batch_op.drop_column('network_name')
        batch_op.drop_column('asn_description')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('country_iso')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_alerts_event_id', type_='foreignkey')
        batch_op.drop_constraint('fk_alerts_ip_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alerts_ip_id'))
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('rule_name')
        batch_op.drop_column('event_id')
        batch_op.drop_column('ip_id')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
