"""Alert model for security alerts generated by the alert engine."""

from datetime import datetime, timezone

from app.extensions import db


class Alert(db.Model):
    """Security alerts generated by the alert engine."""

    __tablename__ = 'alerts'

    id = db.Column(db.Integer, primary_key=True)
    ip_id = db.Column(
        db.Integer, db.ForeignKey('ip_addresses.id'), nullable=True, index=True
    )
    event_id = db.Column(
        db.Integer, db.ForeignKey('security_events.id'), nullable=True
    )
    severity = db.Column(db.String(20))  # LOW, MEDIUM, HIGH, CRITICAL
    title = db.Column(db.String(255))
    description = db.Column(db.Text)
    rule_name = db.Column(db.String(100))
    resolved = db.Column(db.Boolean, default=False)
    resolved_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    event = db.relationship('SecurityEvent', backref='alerts')

    def to_dict(self) -> dict:
        """Serialize the alert to a dictionary.

        Returns:
            dict: Dictionary representation of the alert.
        """
        return {
            'id': self.id,
            'ip_id': self.ip_id,
            'ip': self.ip_ref.ip if self.ip_ref else None,
            'event_id': self.event_id,
            'severity': self.severity,
            'title': self.title,
            'description': self.description,
            'rule_name': self.rule_name,
            'resolved': self.resolved,
            'resolved_at': (
                self.resolved_at.isoformat() if self.resolved_at else None
            ),
            'created_at': (
                self.created_at.isoformat() if self.created_at else None
            ),
        }